### ISSUE TITLE
Применить все замечания первого проекта к текущему

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/ui-website#1]
Если есть время, можно исправлять этот и следующий проект по аналогии с первым по всем пунктам. Если этого не сделать или сделать как попало, то проверка затянется, а замечания все равно будут выданы.

**Comment by Sergio-Ka** [comment]
По факту наворочено много, много прикручено всякого на js чего собственно и не требовалось, а основные пункты замечаний первого проекта выполнены через раз:
1. именование (issue)
2. Не все блоки по бэм, которые есть выделены в папки и оформлены миксинами (например navigation, wrapper, header.
3. Не во все блоки их содержимое передается параметрами, например в миксин news-1 и news-2 не передается текст с содержимым
4. Структура папок проекта очень сложная и запутанная, с учетом того что сам проект достаточно простой. Куча вложенных папок, что в общем-то не требуется. Типа всякие папки fonts и images спрятанные в папку static. Очень сложно вникать, что где находится и в каком месте подключается. В этой связи было бы логичным выделить отдельно элементы самого ui-kit, блоки страницы макета в которых используются эти элементы в соответствии с названиями и весь остальной сайт с его страницами и блоками на которых просто подключаются элементы уже сверстанные для страницы макета.
5. Так же напоминаю, что блоки по бэм должны со всеми своими реализациями находится в одном месте, а не быть размазанными по нескольким папкам. А то там опять какие то папки partials, plugins, static и так далее.

**Comment by performanceArtist** [comment]
Постарался по максимуму убрать лишнее и вложенное, прошёлся более внимательно по другим пунктам. 

По поводу выделения блоков в миксины - а что, если сама страница(к примеру, index или ui) - это блок? Нет же смысла переносить/лишний раз усложнять, если не предполагается её переиспользование?

**Comment by Sergio-Ka** [comment]
Если блок по БЭМ, то уже предполагается переиспользование из самого определения блока в методологии. И не вижу причин не выносить. Другой вопрос, что там когда много страниц можно функции для шаблонизации пользовать (или как они там правельно в паге зовуться?). Ну типа где extends block всякие используются. У тебя же шапка с менюшкой и футер одинаковые везде. Ложишь это все в отдельное место, типа папки source/pages и там уже на каждой такой странице подключаешь соответствующие миксины. Если не понятно, глянь у меня в профиле проект MySite как там это реализовано.

**Comment by performanceArtist** [comment]
Не совсем понял этот комментарий. footer и прочее как раз лежат отдельно в папке layout, потом подключаются в файле layout.pug. Страницы соотвественно все используют этот файл как основу, пользуясь block и extend. Что не так-то?
