### ISSUE TITLE
Margin и padding у блоков

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/ui-website#10]
В соответствии с БЭМ, блоки не могут задавать внешнюю геометрию. У них не могут использоваться margin, а padding могут применяться только для внутренних отступов блоков, а не для того, чтобы оттолкнуть соседние.

Например, вот: 

![Снимок экрана в 2019-07-30 10-05-21](https://user-images.githubusercontent.com/38564412/62108174-118eba00-b2b2-11e9-83ea-6b47a458ff13.png)

Также посмотри **checkmark, steps-slider, slider, pizza, index.**

**Comment by performanceArtist** [comment]
Тут несколько специфичные ситуации - кое-где по смыслу это padding, но его применение нарушит внешний вид. У кнопки margin применяется чтобы её тень не могла залезть на другие элементы - то есть это относится чисто к внешнему виду блока, а не окружающей геометрии. У steps-slider элементы добавляются с js и имеют абсолютное позиционирование => им тоже нужен отступ. У checkmark похожая ситуация - иконка позиционируется абсолютно, и на её месте нужен padding, чтобы она занимало место и не налезала на label.

**Comment by viktoriya-ch** [comment]
У checkmark внутренний отступ можно задать элементу checkmark__label. 

Pizza и index также можно позиционировать, положив контент в элемент блока, либо позиционировать через элемент родительского блока. 

В остальных случаях, если это именно внутренние отступы, то нужно менять margin на padding. Если padding нарушает внешний вид, значит, не хватает элементов внутри блоков. Например, блок steps-slider сейчас у тебя по сути это только дорожка слайдера, но в ней почему-то лежит шкала и бегунок.

**Comment by performanceArtist** [comment]
>блок steps-slider сейчас у тебя по сути это только дорожка слайдера

Почему? Этот блок - просто пустой контейнер с data-атрибутами, который заполняется jquery-плагином. Тут можно разве что обёртку добавить, в которой задать то же самое.

checkmark исправил в последнем коммите, index и pizza изменил в коммите выше. Блоки страниц по-прежнему оборачиваются в .content, но теперь у него есть модификатор .content_center(ed -надо имена поправить).

**Comment by viktoriya-ch** [comment]
> Почему? Этот блок - просто пустой контейнер с data-атрибутами, который заполняется jquery-плагином. 

Ну у тебя сейчас бэкграунд и закругление углов задается именно для блока steps-slider, поэтому его и распирает от паддингов. В таком случае нужно в steps-slider положить элемент steps-slider__track, например, или какое-то более подходящее название, и ему уже задавать дата-атрибуты и бэкграунд, бордер и т.д. А steps-slider просто паддинги установить.

**Comment by performanceArtist** [comment]
Не совсем понял, о каких границах и фоне речь - там этого нет. Сделал обёртку и задал padding.

**Comment by viktoriya-ch** [comment]
Ну ты сейчас перенес в .steps-slider__slider `background: $light-grey;`, вот об этом и была речь. В общем, сейчас все верно.
