### ISSUE TITLE
Именование css

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/ui-website#11]
Вот здесь в стандартах описано, как именовать модификаторы: https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md

Например, в стандартах в качестве некорректного модификатора приводится _error, у тебя как раз такой и аналогичные есть в bubble, video, news и ui. 

Насчет ui тут и вовсе стоит заменить title на блок standart-heading (как ты сделал везде), ведь это он же и есть, а паддинги заголовкам задать при помощи элементов-оберток "ui__slider-title" и т.д.

**Comment by viktoriya-ch** [comment]
И еще сразу здесь, когда будешь поправлять bubble, обрати внимание, что в bubble_label у тебя указано display: absolute, у свойства display нет такого значения, а значит, оно не применилось, скорее всего, это нужно просто удалить.

**Comment by performanceArtist** [comment]
Пока сделал некоторые имена по схеме with-'noun', т.к. на ум ничего не идёт - непонятно, как ещё описать, если это bubble для комментария или он же в качестве подсказки-указателя в slider. display: absolute - недавняя опечатка, убрал. standard-heading к ui добавил.

**Comment by viktoriya-ch** [comment]
Здесь по-прежнему еще не всё

**Comment by performanceArtist** [comment]
А где ещё не верно? Вроде везде проверил. Или with-... тоже нужно заменить?
