### ISSUE TITLE
Обработчики событий

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/ui-website#12]
В соответствии со стандартами, обработчики событий нужно выносить в отдельные функции (пункт 11: https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md).  

Например, в блоках video, order, datepicker, и т.д. В блоке order, к тому же,  дублируется код в обработчиках событий, вынести в одну функцию - и будет гораздо лучше.

![Снимок экрана в 2019-07-30 20-35-24](https://user-images.githubusercontent.com/38564412/62151780-c902eb00-b309-11e9-9988-5197e3b744a7.png)

**Comment by viktoriya-ch** [comment]
В datepicker еще осталось.

**Comment by viktoriya-ch** [comment]
Еще один обработчик

![Снимок экрана в 2019-08-05 15-50-24](https://user-images.githubusercontent.com/38564412/62465945-ce908300-b798-11e9-963f-fb3c62915d1e.png)

**Comment by performanceArtist** [comment]
Поправил.
