### ISSUE TITLE
Именование в js

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/ui-website#13]
Имя переменной должно полно и точно описывать сущность и ее предназначение (https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/naming.md)

Не стоит именовать переменные x, y, s, r, sa. ctx, perc... - из их имен совсем не сразу понятно, что они в себе содержат. (например, блоки pie-chart и ripple)

**Comment by viktoriya-ch** [comment]
В ripple.js остались переменные x,y

**Comment by viktoriya-ch** [comment]
А gh-pages ты не обновлял?

**Comment by performanceArtist** [comment]
Нет ещё - как завтра поправлю страницу с ui, добавлю.

**Comment by viktoriya-ch** [comment]
Просто в локальной версии ripple-эффект на кнопках на данный момент не работает

**Comment by performanceArtist** [comment]
Да, там опечатка была в имени модификатора - исправил.

**Comment by viktoriya-ch** [comment]
Есть еще переменные с некорректными именами:

**Datepicker:**

![Снимок экрана в 2019-08-05 16-17-42](https://user-images.githubusercontent.com/38564412/62467504-9b4ff300-b79c-11e9-8192-4dc0ce1f0541.png)

selected переводится как "выбранный". Переменные принято именовать существительными.

**MessageForm.** То же самое:

`const valid` - валидный. 

**Order**

`const current `- текущий.
`const next` - следующий
