### ISSUE TITLE
Не мутировать параметры

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/ui-website#14]
По стандартам airbnb нельзя мутировать параметры: https://github.com/airbnb/javascript#functions--mutate-params

Проверь message-form

![Снимок экрана в 2019-07-31 13-54-03](https://user-images.githubusercontent.com/38564412/62206593-d4522700-b39a-11e9-8cf0-56778b2693d2.png)

**Comment by performanceArtist** [comment]
Это же манипуляция dom. Оно по-любому чистым не будет. Можно записывать в this.current временно, но сути не поменяет.

**Comment by performanceArtist** [comment]
То есть так и так эта функция нужна для сайд-эффектов. В стандартах речь о нежелательных изменениях, а тут сделано осознанно.

**Comment by viktoriya-ch** [comment]
Хорошо, пусть тогда так останется
