### ISSUE TITLE
Ripple.js

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/ui-website#15]
- В папке блока должны лежать его одноименные pug, css и js. Если твой блок называется button, то и класс должен называться Button, и файл его должен называться так же.

- Если твоя функция debounce не относится ни к какому классу, то почему она лежит в файле класса Ripple?

- Также класс не должен инициализироваться там же, где и объявлен, для этого должен быть отдельный файл.

> все классы, которые используем для поиска по DOM-у должны начинаться с префикса js-

Это всё не только в этом блоке, касается всего проекта.

**Comment by performanceArtist** [comment]
>Если твоя функция debounce не относится ни к какому классу, то почему она лежит в файле класса Ripple?

Пусть будет как статический метод - раз уж нигде больше не используется.

>все классы, которые используем для поиска по DOM-у должны начинаться с префикса js-

Это откуда? В практиках будто нет. И что значит "используем" - если есть хотя бы одна выборка, уже нужен префикс?

**Comment by viktoriya-ch** [comment]
Это из стандартов, раздел jQuery, но на чистом js все те же проблемы - если ты поменяешь в pug  название класса, то поломается скрипт, с префиксом же явно видно, от каких классов зависят скрипты.

**Comment by performanceArtist** [comment]
А что если нужно выбрать какой-нибудь блок без js? К примеру, нужно взять arrow-button - нет же смысла вешать префикс на класс самого блока, если он используется в другом месте?

**Comment by viktoriya-ch** [comment]
> А что если нужно выбрать какой-нибудь блок без js? К примеру, нужно взять arrow-button - нет же смысла вешать префикс на класс самого блока, если он используется в другом месте?

Не совсем понятен вопрос

**Comment by viktoriya-ch** [comment]
Еще вот здесь

![Снимок экрана_2019-08-09_21-49-17](https://user-images.githubusercontent.com/38564412/62801984-94ecae80-baef-11e9-89ff-9146ff0aba4d.png)

**Comment by performanceArtist** [comment]
>Не совсем понятен вопрос

Собственно, он поднят в другом issue(8). Речь о том, как быть, если с блоком внутри другого блока нужно произвести какие-либо действия через js, но притом сам изменяемый блок в js не нуждается.
