### ISSUE TITLE
Выложить изображение для perfectpixel

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/ui-website#2]
Выложить изображение, по которому версталось. Пока визуально элементы набросаны как попало. stages залез на цифры слайдера, сами слайдеры растянулись на всю страницу, а должны быть в одну линию. search и selectmenu разные по ширине и у них разные кнопки по ширине так же, углы у них должны быть скругленные, у инпута поиска при ошибке цвет шрифта должен быть другой. Углы должны быть скругленные и у поля your message формы. Иконки у карты не такие как на макете. arrow и standard buttons не все, что были в макете. Нужно расположить их все с разными видами в нужном количестве. Границы у клеток календаря выглядят странно, так же и и какие-то белые полоски в его заголовке, плюс какие-то пустоты по краям кнопки. Сама кнопка календаря должна по нажатию возвращать на TODAY, а не просто перелистывать вид на текущий месяц. То есть тут нужно сделать функционал для этого самостоятельно, а не использовать штатный встроенный в элемент Календарь плагина.

**Comment by performanceArtist** [comment]
Картинку добавил ([в корень](https://github.com/performanceArtist/ui-website/blob/master/FlatUI.jpg)). Масштаб - 1.25. Мне казалось, тут не нужно настолько строго - всё-таки требовалось сделать компоненты для сайта, а не конкретно страницу, как в первом задании. Но постарался исправить - с календарём пока не совсем ясно, т.к. сложно понять, откуда появились те же полосы. По-моему так даже лучше смотрится, чем всё в кашу. Today сделал - странно, что он по умолчанию не работал. 

По поводу кнопок - из описания макета и именования как я понял, я сделал все варианты. Там три ряда кнопок, но по факту это три состояния - обычное, hover и active(снизу вверх по рядам). Так что сделано соответственно. С arrow-buttons похожая история, но там состояния делятся на обычное, hover и disabled.

**Comment by Sergio-Ka** [comment]
Там как раз таки важный момент в создании внешних блоков и подключении внутренних, это тоже не плохо уметь. А у этих внешних блоков и есть позиционирование, которое по сути и задает позиционирование элементов. То есть выстраивание блоков это еще один пласт знаний, которые необходимо уметь и лучше сейчас, чем потом на реальном проекте. На счет "казалось" и "мне так кажется лучше" - придет клиент и скажет - сделай мне винтажный кукурузник для моей коллекции за 10 млн$, а ты ему через какой-то срок пригоняешь феррари со словами - мне так показалось лучше, да и вообще кому нужна эта рухлядь. Как думаешь, такая ситуация будет нормальной? Для творчества есть остальные страницы сайта. А макет он и есть макет. Выглядит кстати все еще плохо. Суть: сверстать один в один, а потом ощутить всю мощь методологии БЭМ и компонентной верстки и переиспользовать нужные элементы уже на своих страницах без переделки, а только скармливая им свои параметры и тем самым их кастомизируя. На счет кнопок - с натяжкой можно считать что сделано. Хотя в чем проблема для фронтендера выстроить кнопки в несколько рядов и выстроить элементы красиво я не понимаю например, тем более что они компонентами сделаны. Оно такое может быть много в реальной работе, что придется все до пикселей вылизывать - это нормальный рабочий процесс. А вообще там на реализацию я еще посмотрю у кнопок конечно. Потому что риппл например может быть, а может не быть. Кнопка может быть активной или нет, в зависимости от параметров, и по идее на неактивной не должно быть риппла. Все это должно работать навешиванием модификаторов, а там как я сейчас вижу поверхностно реализация не очень. На счет Today теперь нормально. На счет календаря - там есть стили у календаря плагина. Чтобы их переназначить можно сделать папку vendor и в нее скопировать эти стили, а потом их переназначить на свои уже в этом скопированном файле.
Блоки news и events слиплись, блоки search и dropdown тоже. На карте иконки внизу выстроены вертикально.

**Comment by performanceArtist** [comment]
Будто бы всё поправил в последнем коммите.

**Comment by Sergio-Ka** [comment]
Надо бордеры убрать у ячеек календаря.
![image](https://user-images.githubusercontent.com/33621369/59846016-fe223200-9388-11e9-8837-abbaeb582f11.png)
Если будет сделано - это ишью можно закрыть. В остальном теперь нормально более или менее.
