### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/ui-website#3]
Как я уже писал в первом проекте, не использовать имена любых сущностей с числами типа mixin news-1 mixin news-2. Отверить еще раз все замечания касательно именования выданные в первом проекте.

**Comment by Sergio-Ka** [comment]
Что такое bubble? Из названия понять сложно из структуры тоже.

**Comment by performanceArtist** [comment]
Имена поправил. Bubble - это как бы speech-bubble, такая аналогия. То есть это элемент с округленными углами и "хвостиком", внутрь котого можно поместить что угодно(его использует slider, profile, сообщения возле input).
