### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/ui-website#4]
1. Такие вещи по БЭМ не допустимы:
```
  h1,
  h2 {
    font-family: $font;
    font-weight: bold;
    word-spacing: 0.3125rem;
  }

  a {
    text-decoration: none;
    color: #006000;
  }

  a:hover {
    color: #008500;
  }
```
2. Давай определимся на тему наличия компонентов. Если папка components содержит у тебя все компоненты мелкие независимые (ui элементы), которые можно переиспользовать, то где слайдер, pie-chart, percentage? Вообще тут лучше выделять явно компоненты такого рода. А вот footer тут и header имхо лишние. Вообще реализацию страниц и все это, что касается шаблонизатора и сайта лучше вынести в отдельное место, например создать какую-то папку типа pages что ли. Не совсем пойму что такое progressbar и checkmark.

**Comment by performanceArtist** [comment]
> слайдер, pie-chart, percentage

По идее слайдер использует элемент bubble(чтобы обернуть значение), поэтому он не полностью независим. Всё, у чего есть include других компонентов, лежит в папке composite. 

percentage и pie-chart находятся в папке components/chart. pie делается чисто с js-плагином, поэтому для него нет отдельного pug-файла. Файл chart.js в папке экспортирует percentage и pie. Хотя можно в принципе разделить. Не уверен, как лучше сделать, если для элемента нужен только js, но пускай будет в отдельной папке. Можно ещё как вариант сделать миксин, который просто создаёт одинокий div с классом, а js уже пройдёт по всем элементами, но это как-то впустую получится. В остальных случаях хоть что-то кроме него нужно было.

progressbar - это "stages", т.к. он по сути похож на отображение прогресса загрузки например, только здесь отдельные шаги показываются. checkmark - radio/checkbox с галкой(tick/checkmark).

**Comment by Sergio-Ka** [comment]
Честно говоря все очень не очень. Элементы ui должны быть выделены явно, ибо параметры в них ты должен передавать в миксине, которые потом будут data- атрибутами, а js составляющая должна брать данные уже из этих самых data- атрибутов. Это вопрос компонентности. Ты параметры должен  передавать в одном месте. Компонент у тебя - черный ящик, у которого ты знаешь только интерфейс и тебе не интересно на этом уровне абстракций как он устроен внутри и как он выкручивается, чтобы взять данные и от куда он их конкретно берет. Каждый раз когда ты меняешь параметры, ты не должен шарить по всем реализациям компонента, чтобы все параметры привести в соответствие. А это все уже значит как минимум, что у каждого компонента будет pug свой, который в самом простом случае будет оберткой, в которой будут лежать параметры. Это кстати будет логично выглядеть будет вместе с реализацией issue классами ES6. Во-вторых деление на composite и components сомнительно и не понятно для чего сделано. Если чтобы видеть явно компоненты с зависимостями и без - то тут и так видно в файле по наличию директив include. Тут просто проект мелкий, и возможно делить так не стоит. Хотя в общем такие практики используются на больших проектах, правда то что у тебя components обычно зовется elements, а то что composite зовется как раз таки components. Короче здесь ладно, на твое усмотрение. Сами страницы лучше внести в отдельную папку pages, там я уже в другом issue написал. Всякие view layouts будут там лежать. Там ничего лишнего в страницах шаблонных быть не должно, только подключение миксинов. Ну как вариант текст какой-то статичный, который на страницах повторяется.

**Comment by performanceArtist** [comment]
Теперь все страницы выделены как элементы. Подключаются соответственно во views. Как я писал в другом issue, страницы так и лежали отдельно, "расширяя" layout. Сейчас аналогично, но теперь там только подключаются миксины и передаются настройки.
