### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by Sergio-Ka** [performanceArtist/ui-website#5]
1. Переписать всё на классах ES6.
2. Код должен соответствовать стандартам fsd.
3. const jcont = $(cont); константы которые используют jquery должны именоваться начиная с символа `$`.
5. По поводу сокращений типа `e` уже говорил кажется.
4. tickbox и toggles реализовать на чистом css. Задача слишком тривиальная и часто встречающаяся, чтобы тут js использовать. Ну и потом пункт задания о том, что "все, что можно реализовать на чистом html+css, нужно на них и реализовывать" никто не отменял. Там вообще много js, при чем он плохо читается. Там где используется js в блоках должен по хорошему лежать файл который будет частью реализации блока, а уже в нем должны импортироваться какие-то возможности библиотеки, а такие файлы на вроде jquery.progressbar.js плохо читаются и воспринимаются.

Вот для примера реализация блока слайдера
```
class SliderDescrete {

  constructor($element) {
    this.$element = $element;
    this.initSlider();
  }

  getSliderSettings() {
    return {
      min: this.$element.data('min'),
      max: this.$element.data('max'),
      step: this.$element.data('step'),
      value: this.$element.data('value'),
      range: this.$element.data('range'),
    }
  }

  initSlider() {
    this.$element.slider(this.getSliderSettings());

    const $sliderTheme = this.$element.data('theme');
    const $sliderHandle = this.$element.find('.ui-slider-handle');
    const $sliderMinRange = this.$element.find('.ui-slider-range-min');

    $sliderHandle.addClass(`slider-discrete__handle_theme_${$sliderTheme}`);
    $sliderMinRange.addClass(`slider-discrete__range-min_theme_${$sliderTheme}`);
  }
}

$('.js-slider-discrete').each((index, domElement) => {
  new SliderDescrete($(domElement));
});
```

**Comment by Sergio-Ka** [comment]
Вот так pug выглядит:
```
mixin slider-discrete(options = {min: 0, max: 100, step: 25, value: 75, range: "min", theme: "green"})
    -let {min = 0, max = 100, step = 25, value = 75, range = "min", theme = "green"} = options;
    .slider-discrete.js-slider-discrete(data-min= min, data-max= max, data-step= step, data-value= value, data-range= range, data-theme= theme)
    .slider-discrete__scale
        -for (let i = min; i <= max; i += step) {
            .slider-discrete__digit= i
        -}
```

**Comment by Sergio-Ka** [comment]
Это все для лучшего понимания того, что должно быть в итоге и что требуется во втором проекте.

**Comment by performanceArtist** [comment]
>Переписать всё на классах ES6.

То есть "всё"? Там почти везде можно одной функцией обойтись(или даже без неё). Какой должен быть функционал у методов, если создание объектов не требуется? Зачем оно, просто для обёртки? В имплементации выше есть опции, задаваемые через миксины, а для для плагина требуются разве что опции по умолчанию для него(которые у меня прописаны как defaults и складываются с кастомными опциями options).

**Comment by Sergio-Ka** [comment]
Оно затем, что так нужно. Нужно научится мыслить и делать в категориях ООП, чего сейчас явно нет. И лучше это делать как раз с использованием классов ES6, ибо визуально воспринимается лучше, да и вообще считай правила хорошего тона (хотя теоретически можно и классы в функциональном стиле писать, но не надо). Там во многих местах вообще можно было без js обойтись, например pie-charts и percentage делаются на раз миксином pug с помощью svg, однако сделано для чего-то с использованием js. Что кстати нарушает задание о том, что все что можно делать без использования js нужно делать без него. Но тут ладно. А вот если уж использовал js - делай как положено.
На счет функционала методов - как минимум метод инициализации будет у тебя. Конструктор опять же - там могут поля инициализироваться. Это как минимум. Сейчас у тебя для примера если тот же percentage если взять - реализовано плохо. У тебя класс css там один и тот же для каждого элемента используется, а id разные. Во-первых id по БЭМ не допустимы, во-вторых используя классы и создавая для каждого твоего percentage отдельный инстанс ты инкапсулируешь состояние, как следствие ты можешь использовать сколь угодно большое количество однотипных элементов на странице, каждый со своими настройками, и они друг на друга влиять не будут. Это считай основа ООП и его бы хорошо подтянуть. И это же ответ на вопрос "зачем оно?".

**Comment by performanceArtist** [comment]
Добавил классы.

>Там во многих местах вообще можно было без js обойтись, например pie-charts и percentage делаются на раз миксином pug с помощью svg

Даже анимация значений? Этого без js не сделать, насколько я понимаю. И формулировка задания была такая, что оно нужно как раз для работы с плагинами:

>ради этого макет и подбирался, чтобы был опыт экспериментов с подключением jQuery и его плагинов

>создавая для каждого твоего percentage отдельный инстанс ты инкапсулируешь состояние

Если уж на то пошло, функция тоже ограничивает видимость - не вижу различия. Да и всё равно в js классы - функции, "настоящих" классов нет. Вообще я знаю ООП, просто здесь не стал применять сразу. Хотя в некоторых случаях сейчас вижу, что стоило.

**Comment by Sergio-Ka** [comment]
Не смотря на прошедшее время:
1. На классах сделаны только некоторые компоненты
2. Код не удовлетворяет требованиям стандартов в полной мере (тяжеловесные конструкторы например).

**Comment by performanceArtist** [comment]
Раз так принципиально, пусть все будут на классах. Из конструкторов добавление событий и поиск по dom тоже убрал, теперь это вызывается в init-методах.

**Comment by Sergio-Ka** [comment]
1. Здесь debounce это функция, которая навешивается хэндлером в классе. Почему это не метод класса? Если она нужна снаружи - можно вызывать как публичный метод класса.
```
function debounce(func, delay) {
  let inDebounce;
  return function newDebounce(...args) {
    const context = this;
    clearTimeout(inDebounce);
    inDebounce = setTimeout(() => func.apply(context, args), delay);
    return inDebounce;
  };
}

class Ripple {
  constructor(root) {
    this.root = root;

    this.init = this.init.bind(this);
    this.showRipple = this.showRipple.bind(this);
    this.cleanUp = this.cleanUp.bind(this);

    this.init();
  }
```
2. Здесь в конструкторе по прежнему лишнего много. У тебя по хорошему там только поля в this должны прописываться и один-два метода должны вызываться, а все эти поиски по элементу, извлечение каких-то данных выносить в методы. Это кстати надо глянуть по всем классам.
```
class Chart {
  constructor(root, options = {}) {
    this.$root = $(root);
    this.$value = this.$root.find('.chart__text');
    this.data = this.$root.data();
    this.options = options;

    this.init = this.init.bind(this);

    this.init();
  }
```
3. Тут какая-то функция болтается, не понятно что делающая и не понятно почему ее нельзя было сделать методом класса и вызывать метод в конструкторе. Даже если есть веский резон делать это функцией, то как минимум стоит соблюдать правило 1файл = 1модуль = 1 класс (или некая другая сущность), а не все в кучу валить.
```
// multiple colors
(function addColorFeature() {
  const _originalInitFill = $.circleProgress.defaults.initFill;

  $.circleProgress.defaults.initFill = function() {
```
кроме того про такие вещи в стандартах есть i++, там где отсылка к стайлгайду AirBnB
4. Те же замечания, что и выше только в файле stage.js. Только там еще хуже. Класс ради класса. Без методов, все происходит в конструкторе. Такое впечатление, что это сделано для того, чтобы лишь бы формально выполнить issue.
5. Какие-то функции болтаются в файле pizza.js и те же замечания что и выше.

**Comment by performanceArtist** [comment]
>3. Тут какая-то функция болтается,

Эта функция по идее часть плагина(добавляет фичу), я её не писал. Переписал её и stage-компонент. Положил в соседний файл. У pizza тоже перенёс создатель ингредиентов.

**Comment by performanceArtist** [comment]
>Почему это не метод класса?

Потому что она никак к конкретному классу не относится, это просто 'util', который можно где угодно применить.

**Comment by performanceArtist** [comment]
>по хорошему там только поля в this должны прописываться и один-два метода должны вызываться

Сейчас так и должно быть везде.
