### ISSUE TITLE
UI kit page

### ISSUE THREAD

**Issue by alextsk** [performanceArtist/ui-website#6]
а есть gh-page с самим ui-kitом?

**Comment by performanceArtist** [comment]
Он в качестве страницы на сайте лежит [здесь](https://performanceartist.github.io/ui/ui.html).

**Comment by alextsk** [comment]
а можешь сделать его отдельной страницей, и привести по максимуму к макету? цвета, шрифты, позиции. для него пиксель перфект в требованиях

**Comment by performanceArtist** [comment]
Могу сделать, но я уже подогнал более-менее и так, по тем же позициям/пропорциям. Шрифт вроде тот, там отличается разве что из-за размера пробелов и отступов между буквами, можно попробовать исправить. Да, цвета другие, поэтому как раз он лежит на самом сайте, чтобы было видно, как оно смотрится на фоне. По заданию разве всё прямо должно совпадать? Если так, тогда уж весь сайт надо переделывать. На самом деле не так сложно, т.к. цвета заданы через переменные, просто жалко - подбирал всё-таки.

**Comment by alextsk** [comment]
нет сайт не должен сопадать - это твой креатив, к нему только требование использовать компоненты, тут как раз их можно модифицировать и свои цвета даже приветствуются. 
а страничка с китом должна, она не часть сайта. так проще ошибки находить 

по ошибкам, сейчас например 
стрелки не по центру, 
в stages тоже смещены цифры и лишнее выделение
в опциях нет списка (на макете он есть)
![image](https://user-images.githubusercontent.com/16453186/59905436-6d9f2c80-9430-11e9-92f9-17497ae6d409.png)
когда нет лейбла дырки все же не должно быть
с календарем что то не то
просто в контексте сайта сложно сказать это ошибка или модификация

**Comment by performanceArtist** [comment]
>стрелки не по центру

Разве? По виду вроде по центру. Речь же об arrow buttons, так?

>в опциях нет списка (на макете он есть)

Dropdown на макете закрыт, там опций нет.

>когда нет лейбла дырки все же не должно быть

Какой дырки? Места справа? Мне так показалось аккуратнее. Нужно тогда инпуты растянуть?

>с календарем что то не то

Что?

>просто в контексте сайта сложно сказать это ошибка или модификация

Это элементы "как есть", в пределах ui-kit(article с ui-классом). То, что он просто лежит на сайте и там сверху хедер и снизу футер ничего не значит.

**Comment by performanceArtist** [comment]
>в stages тоже смещены цифры и лишнее выделение

Цифры по центру, я этого не вижу. Если там что не совпало, то это потому что на макете этот элемент кривой, а здесь длины заданы в процентах.

**Comment by alextsk** [comment]
> в stages тоже смещены цифры

сейчас посмотрел - норм, про цифры вычеркиваем
проценты тоже норм, макет кривой

**Comment by alextsk** [comment]
> Dropdown на макете закрыт, там опций нет.

макет в psd, там есть слои

> Нужно тогда инпуты растянуть?

почему бы и нет

стрелки - сложно сказать, есть ощущение что они выше центра

> но я уже подогнал более-менее и так, по тем же позициям/пропорциям

![screencapture-performanceartist-github-io-ui-ui-html-2019-06-23-02_16_30](https://user-images.githubusercontent.com/16453186/59968002-18146e00-955d-11e9-951b-d255360085dc.png)

**Comment by performanceArtist** [comment]
Масштаб - 1.25, должен чётко подходить по границам. Поправил упомянутое + слегка подогнал ещё, хотя там и так было не слишком всё плохо, думаю в масштабе дело.

**Comment by alextsk** [comment]
может быть, я по размеру первого заголовка подгонял

сделай все же отдельную страницу, и ссылку в ридми на нее

**Comment by alextsk** [comment]
да 1.25 ближе, но все же не пиксель перфект. слайдер уехал, в чартах шрифт другой
и похоже изменения ты не деплоил еще, подожду финального варианта)

**Comment by alextsk** [comment]
если менять размер шрифта в корне слайдер странно себя ведет, там все на rem?
 
![image](https://user-images.githubusercontent.com/16453186/60095327-7cf7e000-9778-11e9-9143-b11dbf276290.png)

**Comment by performanceArtist** [comment]
>если менять размер шрифта в корне слайдер странно себя ведет, там все на rem?

Это слайдер сделан поверх range-input-а, там с позиционированием проблемы - приходится подгонять всякими offset-ами и множителями. Можно будет заменить на тот же новый плагин с другими стилями.

**Comment by Sergio-Ka** [comment]
Поправь эти два места и можешь закрыть этот issue
![image](https://user-images.githubusercontent.com/33621369/62027933-2ebb7e00-b209-11e9-91bd-f034845b3776.png)
![image](https://user-images.githubusercontent.com/33621369/62027983-56124b00-b209-11e9-8d1c-bc0be47a0ac1.png)

**Comment by Sergio-Ka** [comment]
Даже если не принимать во внимание расположение элементов (хотя это странно для человека, который хочет зарабатывать версткой, что он не может какие-то пиксели подогнать), то как минимум с messaging явно пиксель перфект не соблюдается. Может быть стоит все таки поставить плагин в браузер, и проверять самому на сколько это все совпадает?

![image](https://user-images.githubusercontent.com/33621369/62181922-17060600-b37f-11e9-973b-97cabc0c1b8b.png)

**Comment by performanceArtist** [comment]
Я говорил, что не могу? Естественно при большом количестве изменений там что-то поплывёт. Предварительно сказали, что так пойдёт - я больше обратил внимание на исправления по коду. Подогнать всегда можно успеть. Сам макет кривой - те же заголовки просто по центру не оставить. В этом по-моему недостаток этого ui-kit - всё вместе лежит с кучей отступов поверх, которые там просто для соответствия макету. У messaging явно не всё так далеко, когда я у себя смотрю. И у меня не настолько хороший глазомер, чтобы всё это время без плагина подгонять.

**Comment by Sergio-Ka** [comment]
Вообще проверяющим, и мне в частности относительно ровно, про то, кто и что говорит. За человека говорят поступки. В данном случае проекты и их исполнение. И для фронтендера одно из основных умений - это верстать в соответствии с макетом. Согласись, странно, если заказчик принесет один макет, а ты сверстаешь как тебе захотелось и я писал уже об этом в другом проекте. К чему было воду лить, ту что выше, если по итогу ты все равно привел в целом все к виду того макета, что был изначально? Можно было просто в течение недели после выдачи замечания всё сделать в соответствии с изначальным заданием и давно закрыть вопрос. Закрывай issue.
