### ISSUE TITLE
Примеси

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/ui-website#7]
По стандартам, нельзя использовать примеси, пункт 5 и 6: https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md

В данном случае ты можешь создать отдельный компонент для заголовка и добавить ему модификатор, либо использовать обертку

![Снимок экрана в 2019-07-29 22-26-04](https://user-images.githubusercontent.com/38564412/62076644-e162ff00-b250-11e9-9cf1-0454b335fcc7.png)

То же самое для других блоков, где используются примеси.

**Comment by performanceArtist** [comment]
Сделал так - теперь это один элемент `ui__title` с модификаторами вроде `ui__title.ui__title_video`. Будто бы глюк какой-то происходит, когда два issue упоминаешь - почему-то одно закрывается - не в первый раз такое замечаю.

**Comment by viktoriya-ch** [comment]
У те6я в блоке contact (который на скриншоте), а также в feedback, index и order все еще присутствует "standard-heading". Здесь, наверное, проще вынести его в отдельный блок, раз он так часто используется, чтобы не дублировать везде один и тот же css.
