### ISSUE TITLE
Компонентность

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/ui-website#8]
Каждый блок должен лежать в своей отдельной папке, кроме того, название папки, блока, файла стилей и миксина должны совпадать. 

- Сейчас у тебя в миксине standart-button лежит блок button.

- В файле slider.pug у тебя вообще лежит два блока. По идее, это можно сделать одним миксином. Точно так же в файле news.pug у тебя лежит два блока, причем в блоке .event-news у тебя лежат элементы из блока .news, по БЭМ такого быть точно не должно. 

![Снимок экрана в 2019-07-29 22-54-41](https://user-images.githubusercontent.com/38564412/62077953-0efd7780-b254-11e9-94a4-81f9456914ea.png)

**Comment by viktoriya-ch** [comment]
В файле order.pug блок button почему-то используется без миксина.

![Снимок экрана в 2019-07-29 23-09-34](https://user-images.githubusercontent.com/38564412/62078891-466d2380-b256-11e9-82cb-0282e6e3af73.png)

**Comment by viktoriya-ch** [comment]
В стилях блока не должно быть стилей других блоков, каждый блок должен быть независим. Например: 

![Снимок экрана в 2019-07-29 23-26-34](https://user-images.githubusercontent.com/38564412/62080013-7ddccf80-b258-11e9-8cb3-3883ddfe6280.png)

Проверь также блоки **profile, chat, comment, pizza, order**, и вообще везде, может, где-то еще есть такое.

**Comment by performanceArtist** [comment]
Основные правки внёс, ещё чуть позже проверю. С news ещё подумаю, как сделать лучше. slider разделил, т.к. там имплементация сильно отличается. standard-button теперь просто button - в рамках проекта всё равно ни с чем не спутаешь. В order сделал кнопку с миксином. Все стили bubble теперь задаются через модификаторы(возможно, тоже стоит пересмотреть).

**Comment by viktoriya-ch** [comment]
В блоке .message-form блок .button используется без миксина

**Comment by viktoriya-ch** [comment]
Блок .order: что такое .status__bubble, это чей-то элемент?

![Снимок экрана в 2019-07-30 14-59-55](https://user-images.githubusercontent.com/38564412/62127530-f2f0e900-b2da-11e9-82e7-069a99b56c12.png)

**Comment by performanceArtist** [comment]
Это артефакт от старой имплементации, он там не нужен.

**Comment by viktoriya-ch** [comment]
Осталось вот это исправить:

> В блоке .message-form блок .button используется без миксина

**Comment by viktoriya-ch** [comment]
В **order.js** у тебя блок лезет в другой блок и напрямую производит с ним какие-то действия. То же самое в **pizza.js**

![Снимок экрана_2019-08-09_21-52-35](https://user-images.githubusercontent.com/38564412/62802206-09bfe880-baf0-11e9-9afc-5b142edf58df.png)

![Снимок экрана_2019-08-09_21-53-14](https://user-images.githubusercontent.com/38564412/62802249-1f351280-baf0-11e9-8012-69795febdda5.png)

**Comment by performanceArtist** [comment]
А в чём тут проблема? Что такого страшного в добавлении события или изменении модификатора? Как это иначе сделать?

**Comment by performanceArtist** [comment]
Могу предположить, речь о том, что этот функционал должен быть в классе компонента, но нужно ли это здесь, если сам по себе компонент в js не нуждается?

**Comment by viktoriya-ch** [comment]
> А в чём тут проблема?

Ну, например, ты решишь, что класс arrow-button на самом деле должен называться nav-button, а в итоге неожиданно поломается pizza.js. В БЭМ для взаимодействия между блоками предлагаются события и публичные методы.

**Comment by performanceArtist** [comment]
А события выходит тоже выносить нужно, даже если они ничего в самом блоке не меняют?

**Comment by viktoriya-ch** [comment]
**Order.js** все еще добавляет классы Stage.

> А события выходит тоже выносить нужно, даже если они ничего в самом блоке не меняют?

События, думаю, должны быть у блока, с **arrow-button** хорошо получилось.

Из **pizza.js** лучше бы вынести создание инстансов в **init.js** и передавать их параметрами, и еще передавать pie-chart и chart, чтобы всегда была возможность поменять компоненты, не ковыряя класс.

**Comment by performanceArtist** [comment]
>События, думаю, должны быть у блока

Но не создавать же для dropdown класс с одним методом-обработчиком события, если он сам в нём не нуждается? Здесь мне кажется не страшно использовать onChange.

>Из pizza.js лучше бы вынести создание инстансов в init.js

Создание ингредиентов то есть? Тут по задумке они должны быть напрямую недоступны, также как и pie-chart/chart - компонент получает только названия, рейтинг и названия ингредиентов, а дальше уже сам разбирается. Зачем менять chart снаружи, если у него вполне конкретная роль - определённым образом отображать рейтинг? Разве что цвета другие можно передать. У pie-chart тоже поведение завязано на отрисовку ингредиентов разными цветами, а цвета/значения как раз задаются в атрибутах - больше ничего не требуется.

**Comment by performanceArtist** [comment]
Хотя если так подумать, dropdown-у в общем не помешает метод для оповещения об изменениях. Сейчас в order компоненты изменяются только через методы.
