### ISSUE TITLE
Повторяется имя блока в scss

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/ui-website#9]
В препроцессорах не стоит писать каждый раз заново имя блока, нужно ссылаться на него через &, это и читаемость улучшит, и если имя блока поменяется, тебе не придется изменять его во всех модификаторах и элементах. Посмотри arrow-button.scss и bubble.scss, если еще где-то встретится, то тоже нужно исправить.

**Comment by viktoriya-ch** [comment]
Также желательно писать медиа-запросы внутри блоков и элементов, к которым они относятся, а не в конце файла, это тоже поможет избежать дублирования имени. Пример можно посмотреть в документации: https://sass-scss.ru/documentation/pravila_i_direktivi/direktiva_media.html

**Comment by performanceArtist** [comment]
А как быть с модификаторами тогда? Если я задам к примеру &_left для arrow-button, то & внутри будет ссылаться на .arrow__button_left. То есть придётся писать как-то так:
```
.arrow-button {
  &_left {
    .arrow-button {
      &__arrow {
        ...
      }
  }
}

**Comment by viktoriya-ch** [comment]
Можно на верхнем уровне сохранить arrow-button в переменную вот так: `$b: &;`
И там, где более одного уровня вложенности, вместо амерсанда использовать эту переменную.  Примерно так:

```
.arrow-button {
  //// какой-то код
  $b: &;

  &_left {
    #{$b}__arrow {
      /// какой-то код
    }
  }
}
```

**Comment by performanceArtist** [comment]
Не очень красиво конечно, напоминает `const that = this;`, но работает - спасибо за подсказку.

**Comment by viktoriya-ch** [comment]
Есть еще вариант без вложенности:

```
.arrow-button {
  &_left &__arrow {
        ...
  }
}
```

**Comment by performanceArtist** [comment]
Думаю, такой вариант оптимален:
```
&_left & {
    &__arrow {
        ...
    }
}
```
Несколько неочевидно, но работает без лишних переменных, к тому же вариант с переменной повышает специфичность селектора.
